# Generated by Django 3.2.7 on 2021-09-13 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfapp', '0002_rename_images_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='image',
            new_name='course',
        ),
    ]
